batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: ./
train_epochs: 100
train_workers: 20
vocab: n +.kZUSxd9#pK'rH;h25*,jfD46MB3sXCvzWNw:ciYLJQIEO&og"mAVaRGT)1bl0FtP7!?/u-eq(8y
width: 1408
